// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1f8Za9mYkf3O4LMHff643odGqNd09EeI',
    appId: '1:755863108720:web:41a213e88b04e4510548b5',
    messagingSenderId: '755863108720',
    projectId: 'safecircle-8e2bd',
    authDomain: 'safecircle-8e2bd.firebaseapp.com',
    storageBucket: 'safecircle-8e2bd.appspot.com',
    measurementId: 'G-0L8YXFTLEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJa0h_ZrAyxfPO5rbuDJMBJHHl1ijM8Q',
    appId: '1:755863108720:android:20b14f4e524d16600548b5',
    messagingSenderId: '755863108720',
    projectId: 'safecircle-8e2bd',
    storageBucket: 'safecircle-8e2bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMEMYtx7Ou1v-MnrLMeazyY2jw0nCt2I',
    appId: '1:755863108720:ios:94d9a36176bc1c000548b5',
    messagingSenderId: '755863108720',
    projectId: 'safecircle-8e2bd',
    storageBucket: 'safecircle-8e2bd.appspot.com',
    iosBundleId: 'com.example.womanSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsMEMYtx7Ou1v-MnrLMeazyY2jw0nCt2I',
    appId: '1:755863108720:ios:94d9a36176bc1c000548b5',
    messagingSenderId: '755863108720',
    projectId: 'safecircle-8e2bd',
    storageBucket: 'safecircle-8e2bd.appspot.com',
    iosBundleId: 'com.example.womanSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1f8Za9mYkf3O4LMHff643odGqNd09EeI',
    appId: '1:755863108720:web:e12a9d162f436c9e0548b5',
    messagingSenderId: '755863108720',
    projectId: 'safecircle-8e2bd',
    authDomain: 'safecircle-8e2bd.firebaseapp.com',
    storageBucket: 'safecircle-8e2bd.appspot.com',
    measurementId: 'G-J9285RT2Q7',
  );
}
